### ISSUE TITLE
iocage-tasmoadmin with php7.4 or 7.3?

### ISSUE THREAD

**Issue by joachimarp** [tprelog/iocage-tasmoadmin#4]
Is it possible to use tasmoadmin with PHP7.4 or 7.3?
When installing under TrueNAS 12.x I get an error message about PHP7.2.
PHP7.2 is no longer supported by FreeBSD.

TasmoAdmin plugin for FreeNAS 11 using nginx and php72 ... message reports reads: Install Error: tasmoadmin had a failure Exception: RuntimeError Message: pkg error: - php72 :,php72-curl :,php72-filter :,php72-json :,php72-session :,php72-zip : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed.

**Comment by tprelog** [comment]
Hi @joachimarp - thanks for reporting this :slightly_smiling_face:

I switched the manifest to PHP7.4, and it appears to have been merged to the current release.

- TasmoAdmin should be working again for 12.x releases on TrueNAS Core.
- Personally, I am no longer supporting the 11.x release versions used by FreeNAS.

**Comment by joachimarp** [comment]
> Hi @joachimarp - thanks for reporting this 🙂
> 
> I switched the manifest to PHP7.4, and it appears to have been merged to the current release.
> 
> * TasmoAdmin should be working again for 12.x releases on TrueNAS Core.
> * Personally, I am no longer supporting the 11.x release versions used by FreeNAS.

THX, it works!
