### ISSUE TITLE
TasmoAdmin has a missing configuration, please check that the dataset is mounted.

### ISSUE THREAD

**Issue by elyobelyob** [tprelog/iocage-tasmoadmin#5]
Trying a fresh install on TrueNAS-12.0-U2.1

"Install
Error: Jail: TasmoAdmin has a missing configuration, please check that the dataset is mounted."

All I'm setting in the setup is the name and a fixed IP address ... am I missing something?

Thanks

**Comment by tprelog** [comment]
This is an upstream issue. I've seen other user report the same issue with other plugins. (Sorry I don't have link handy, but I _think_ it was in TrueNAS forums if you want to look)

As a test, can you try giving the jail a different name ? Use something random, that you've never used before.

**Comment by elyobelyob** [comment]
<img width="1890" alt="Screenshot 2021-04-30 at 22 48 57" src="https://user-images.githubusercontent.com/298022/116757668-6bcc2a00-aa06-11eb-83e7-3e1669135523.png">

**Comment by elyobelyob** [comment]
<img width="664" alt="Screenshot 2021-04-30 at 22 48 46" src="https://user-images.githubusercontent.com/298022/116757698-7c7ca000-aa06-11eb-8d83-603fc5782761.png">

**Comment by elyobelyob** [comment]
<img width="591" alt="Screenshot 2021-04-30 at 22 39 18" src="https://user-images.githubusercontent.com/298022/116757737-94542400-aa06-11eb-9182-b9983ae784ce.png">

**Comment by elyobelyob** [comment]
It just hasn't worked ... 
Tried my best ...

**Comment by tprelog** [comment]
For the error it already exist, you can try the following... (not a typo, run it twice)

```bash
iocage destroy -f $JAIL_NAME
iocage destroy -f $JAIL_NAME
```


For the missing configuration, have you tried selecting Community then press `REFRESH INDEX` button on the Plugins page?

Sorry I'm not able to be more helpful... I've currently switch my server over to TrueNAS SCALE, so ATM I don't have any way to verify or try to reproduce this myself.

**Comment by elyobelyob** [comment]
Leaving DHCP on fixed the issue. This is mentioned elsewhere with different plugins, so, yes an upstream issue.

**Comment by elyobelyob** [comment]
Closing due to upstream issue
